#!/bin/sh

# Check if .fonts exists
if [ ! -d ~/.fonts ]; then
	mkdir ~/.fonts
fi

cp -t ~/.fonts *

# install the fonts

mkfontdir ~/.fonts
mkfontscale ~/.fonts
xset +fp ~/.fonts
xset fp rehash
fc-cache -fv
